Suppress NoClassDefError of AccessibleObject on Linux
The class only exists on Linux. It missing does not seem to have an impact
on the application. However, the stack trace is usually reported with
arbitrary other bugs.

Issue: https://stackoverflow.com/questions/56088037/java-lang-noclassdeffounderror-org-eclipse-swt-accessibility-accessibleobject-o
Issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572060